//! Generated code (project ADR-0011, Plan-0002 WP8.1).
//!
//! `debug_protocol` is regenerated by `cargo run -p grimoire_schemagen -- generate` from
//! `schema/debug_protocol_v1.gschema`; do not edit it by hand (see that file's own header
//! comment, or `grimoire_schemagen`'s crate docs for the compiler that writes it).
//!
//! This one-line glue module is itself hand-written and not regenerated: `grimoire_schemagen`
//! only ever overwrites the single file it owns (`debug_protocol.rs`), never the module tree
//! around it, so adding a second schema targeting this crate would mean adding a second `pub mod`
//! line here by hand, the same way this one was added.

pub mod debug_protocol;
