//! Generated code (project ADR-0011, Plan-0002 WP8.1).
//!
//! `pack_manifest` is regenerated by `cargo run -p grimoire_schemagen -- generate` from
//! `schema/pack_manifest_v1.gschema`; do not edit it by hand (see that file's own header comment,
//! or `grimoire_schemagen`'s crate docs for the compiler that writes it).
//!
//! [`pack_manifest::PackManifestBody`] is the manifest codec of [`crate::PackReader`] and
//! [`crate::PackWriter`] (Plan-0002 WP8.3); its own round-trip and golden-fixture tests keep
//! checking it on its own as well.
//!
//! This one-line glue module is itself hand-written and not regenerated, the same way
//! `grimoire_debug`'s sibling module is (see that crate's own `src/generated.rs` for why).

pub mod pack_manifest;
