//! Rust emitter (project ADR-0011): turns a [`Schema`] into one checked-in `.rs` file with plain
//! Rust structs/enums, an `encode`/`decode` pair per struct following contract §2 rule 9 exactly,
//! and a small private `Reader`/`Writer` codec helper the generated `encode`/`decode` bodies call
//! into.
//!
//! The output never depends on the schema source text again (only on the [`Schema`] IR), never
//! embeds a timestamp, tool version or absolute path (project ADR-0011 "Negativ": the CI drift
//! check must be identical on every OS and every run), and is written already close to `rustfmt`
//! style — the CI drift check still runs `cargo fmt --all` after regenerating, so exact spacing
//! here is a readability nicety, not a correctness requirement.

use crate::ir::{EnumDef, EnumWidth, ErrorType, Item, Schema, StructDef, TypeRef};
use std::fmt::Write as _;

/// Renders `schema` as a complete, self-contained Rust source file.
///
/// # Errors
/// Returns an error only if a [`TypeRef::Named`] cannot be resolved against `schema.items` — the
/// same check [`crate::parser::parse`] already performs, repeated here so this function has no
/// unchecked precondition of its own (defence in depth for a schema built by hand rather than
/// through the parser, e.g. in a test).
pub fn emit(schema: &Schema) -> Result<String, String> {
    let error_ident = error_type_ident(schema);
    let mut out = String::new();

    write_header(&mut out, schema);
    if let ErrorType::External(path) = &schema.error_type {
        let _ = writeln!(out, "use {path};");
        out.push('\n');
    }
    write_codec_support(&mut out, &error_ident);

    if let ErrorType::SelfContained = &schema.error_type {
        write_self_contained_error(&mut out, &error_ident, schema);
    }

    for item in &schema.items {
        match item {
            Item::Enum(e) => write_enum(&mut out, e)?,
            Item::Struct(s) => write_struct(&mut out, s, schema, &error_ident)?,
        }
    }

    if !schema.messages.is_empty() {
        write_catalogue(&mut out, schema);
    }

    Ok(out)
}

/// The bare Rust identifier `encode`/`decode` signatures use for this schema's error type: either
/// the last path segment of an [`ErrorType::External`] path, or `<PascalName>Error` for
/// [`ErrorType::SelfContained`].
fn error_type_ident(schema: &Schema) -> String {
    match &schema.error_type {
        ErrorType::External(path) => path.rsplit("::").next().unwrap_or(path.as_str()).to_owned(),
        ErrorType::SelfContained => format!("{}Error", pascal_case(&schema.name)),
    }
}

fn pascal_case(snake: &str) -> String {
    snake
        .split(['_', '-'])
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn write_doc(out: &mut String, indent: &str, doc: &[String]) {
    if doc.is_empty() {
        // missing_docs is a hard error under `-D warnings` (workspace.lints.rust); every public
        // item this emitter writes must carry something, even a schema author who forgot a doc
        // string.
        let _ = writeln!(out, "{indent}/// (undocumented in the schema source)");
        return;
    }
    for line in doc {
        let _ = writeln!(out, "{indent}/// {line}");
    }
}

fn write_header(out: &mut String, schema: &Schema) {
    let _ = writeln!(
        out,
        "// @generated by grimoire_schemagen from {}. Do not edit by hand:",
        schema.source_path
    );
    let _ = writeln!(
        out,
        "// `cargo run -p grimoire_schemagen -- generate` regenerates this file, and"
    );
    let _ = writeln!(
        out,
        "// .github/scripts/check-schemagen-drift.sh fails CI if that would change it."
    );
    let _ = writeln!(out, "//! Generated payload types for `{}`.", schema.name);
    let _ = writeln!(out, "//!");
    if schema.doc.is_empty() {
        let _ = writeln!(
            out,
            "//! Format version {} (see the schema source for details).",
            schema.version
        );
    } else {
        for line in &schema.doc {
            let _ = writeln!(out, "//! {line}");
        }
        let _ = writeln!(out, "//!");
        let _ = writeln!(out, "//! Format version {}.", schema.version);
    }
    out.push('\n');
}

/// `Reader`/`Writer`: a small bounds-checked codec helper, emitted fresh into every generated
/// file rather than shared from a hand-written module, so each generated file stays a single,
/// independently reviewable unit that only reaches outside itself for the one error type named
/// by the schema's `error_type` directive (contract §2 rule 9's length-before-allocation and
/// no-panic rules live here, once, instead of once per field).
fn write_codec_support(out: &mut String, error_ident: &str) {
    let _ = write!(
        out,
        r#"
/// Bounds-checked little-endian cursor for decoding (contract §2 rule 9): every length or count
/// is checked against a documented maximum, and every read against the bytes actually remaining,
/// before anything is allocated; never panics on any input.
struct Reader<'a> {{
    bytes: &'a [u8],
    pos: usize,
}}

// Not every schema's fields exercise every accessor below (e.g. a schema with no `Str16` field
// never calls `str_u16`): this is one shared, generic codec toolkit emitted per file rather than
// one written by hand per schema, so an unused method here says nothing about the generated
// `encode`/`decode` functions that do use the rest of it.
#[allow(dead_code)]
impl<'a> Reader<'a> {{
    fn new(bytes: &'a [u8]) -> Self {{
        Self {{ bytes, pos: 0 }}
    }}

    fn remaining(&self) -> usize {{
        self.bytes.len() - self.pos
    }}

    fn take(&mut self, len: usize) -> Result<&'a [u8], {error_ident}> {{
        match self.pos.checked_add(len) {{
            Some(end) if end <= self.bytes.len() => {{
                let slice = &self.bytes[self.pos..end];
                self.pos = end;
                Ok(slice)
            }}
            _ => Err({error_ident}::UnexpectedEnd {{
                offset: self.pos,
                needed: len,
                available: self.bytes.len() - self.pos,
            }}),
        }}
    }}

    fn u8(&mut self) -> Result<u8, {error_ident}> {{
        Ok(self.take(1)?[0])
    }}

    fn u16(&mut self) -> Result<u16, {error_ident}> {{
        let b = self.take(2)?;
        Ok(u16::from_le_bytes([b[0], b[1]]))
    }}

    fn u32(&mut self) -> Result<u32, {error_ident}> {{
        let b = self.take(4)?;
        Ok(u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }}

    fn u64(&mut self) -> Result<u64, {error_ident}> {{
        let b = self.take(8)?;
        Ok(u64::from_le_bytes([
            b[0], b[1], b[2], b[3], b[4], b[5], b[6], b[7],
        ]))
    }}

    fn f32(&mut self) -> Result<f32, {error_ident}> {{
        let b = self.take(4)?;
        Ok(f32::from_le_bytes([b[0], b[1], b[2], b[3]]))
    }}

    /// Decodes a `bool` (contract §13: one `u8`, `0` or `1`); any other byte is `InvalidEnum`,
    /// the same treatment `option_tag` gives its own `u8` tag. `UnexpectedEnd` (from reading the
    /// underlying byte) carries no field name (contract §13), but `InvalidEnum` does, so this is
    /// the first method in this reader that needs one.
    fn bool(&mut self, field: &'static str) -> Result<bool, {error_ident}> {{
        match self.u8()? {{
            0 => Ok(false),
            1 => Ok(true),
            value => Err({error_ident}::InvalidEnum {{
                field,
                value: u32::from(value),
            }}),
        }}
    }}

    /// Decodes an `Option<T>` tag (contract §13: `u8`, `0` = absent, `1` = present). Identical
    /// wire shape to [`Reader::bool`]; kept as its own method so generated call sites read as
    /// "decoding a presence tag", not "decoding a boolean field".
    fn option_tag(&mut self, field: &'static str) -> Result<bool, {error_ident}> {{
        self.bool(field)
    }}

    fn array<const N: usize>(&mut self) -> Result<[u8; N], {error_ident}> {{
        let slice = self.take(N)?;
        let mut out = [0u8; N];
        out.copy_from_slice(slice);
        Ok(out)
    }}

    fn array_f32<const N: usize>(&mut self) -> Result<[f32; N], {error_ident}> {{
        let mut out = [0.0f32; N];
        for slot in &mut out {{
            *slot = self.f32()?;
        }}
        Ok(out)
    }}

    /// Decodes `Str≤max`/`Str16≤max` once the `u32`/`u16` length prefix is already known
    /// (contract §13/§12): `raw_len > max` fails with `FieldTooLong` before the length is even
    /// checked against the bytes remaining, and the UTF-8 bytes are copied only after both length
    /// checks pass.
    fn string(
        &mut self,
        field: &'static str,
        max: usize,
        raw_len: usize,
    ) -> Result<String, {error_ident}> {{
        if raw_len > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: raw_len,
                max,
            }});
        }}
        let bytes = self.take(raw_len)?;
        String::from_utf8(bytes.to_vec()).map_err(|_| {error_ident}::InvalidUtf8 {{ field }})
    }}

    fn str_u32(&mut self, field: &'static str, max: usize) -> Result<String, {error_ident}> {{
        let raw_len = self.u32()? as usize;
        self.string(field, max, raw_len)
    }}

    fn str_u16(&mut self, field: &'static str, max: usize) -> Result<String, {error_ident}> {{
        let raw_len = usize::from(self.u16()?);
        self.string(field, max, raw_len)
    }}

    fn bytes_u32(&mut self, field: &'static str, max: usize) -> Result<Vec<u8>, {error_ident}> {{
        let raw_len = self.u32()? as usize;
        if raw_len > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: raw_len,
                max,
            }});
        }}
        Ok(self.take(raw_len)?.to_vec())
    }}

    /// Decodes a `Vec≤max<T>` element count (contract §13): the raw `u32` count is checked
    /// against `max` before the caller allocates a `Vec` with that capacity, so an oversized
    /// declared count (e.g. `u32::MAX`) never reaches an allocation — it fails here instead.
    fn count_u32(&mut self, field: &'static str, max: usize) -> Result<usize, {error_ident}> {{
        let raw_count = self.u32()? as usize;
        if raw_count > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: raw_count,
                max,
            }});
        }}
        Ok(raw_count)
    }}

    /// Fails with `TrailingBytes` unless every byte has been consumed (contract §13: "keine
    /// Rest-Bytes"). Only the outermost `decode` of a payload calls this; a struct nested inside
    /// a `Vec` or `Option` decodes with [`Reader`] shared by its parent and never checks this on
    /// its own.
    fn finish(&self) -> Result<(), {error_ident}> {{
        if self.remaining() == 0 {{
            Ok(())
        }} else {{
            Err({error_ident}::TrailingBytes {{
                extra: self.remaining(),
            }})
        }}
    }}
}}

/// Append-only little-endian byte writer for encoding (contract §13). Every method that can
/// exceed a declared maximum returns `Err` before writing anything for that field; fields already
/// written for earlier struct fields are left in `out` on error, which is harmless because a
/// caller only uses `out` after a fully `Ok` `encode` call (the same convention
/// `grimoire_debug::encode_frame` already uses for the frame envelope).
struct Writer<'a> {{
    out: &'a mut Vec<u8>,
}}

// Same rationale as `Reader`'s `#[allow(dead_code)]` above: not every schema's fields exercise
// every writer method.
#[allow(dead_code)]
impl<'a> Writer<'a> {{
    fn new(out: &'a mut Vec<u8>) -> Self {{
        Self {{ out }}
    }}

    fn u8(&mut self, value: u8) {{
        self.out.push(value);
    }}

    fn u16(&mut self, value: u16) {{
        self.out.extend_from_slice(&value.to_le_bytes());
    }}

    fn u32(&mut self, value: u32) {{
        self.out.extend_from_slice(&value.to_le_bytes());
    }}

    fn u64(&mut self, value: u64) {{
        self.out.extend_from_slice(&value.to_le_bytes());
    }}

    fn f32(&mut self, value: f32) {{
        self.out.extend_from_slice(&value.to_le_bytes());
    }}

    fn bool(&mut self, value: bool) {{
        self.u8(u8::from(value));
    }}

    fn option_tag(&mut self, present: bool) {{
        self.bool(present);
    }}

    fn array<const N: usize>(&mut self, value: &[u8; N]) {{
        self.out.extend_from_slice(value);
    }}

    fn array_f32<const N: usize>(&mut self, value: &[f32; N]) {{
        for v in value {{
            self.f32(*v);
        }}
    }}

    fn str_u32(
        &mut self,
        field: &'static str,
        max: usize,
        value: &str,
    ) -> Result<(), {error_ident}> {{
        let bytes = value.as_bytes();
        if bytes.len() > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: bytes.len(),
                max,
            }});
        }}
        self.u32(bytes.len() as u32);
        self.out.extend_from_slice(bytes);
        Ok(())
    }}

    fn str_u16(
        &mut self,
        field: &'static str,
        max: usize,
        value: &str,
    ) -> Result<(), {error_ident}> {{
        let bytes = value.as_bytes();
        if bytes.len() > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: bytes.len(),
                max,
            }});
        }}
        // `bytes.len() <= max` and every `str16` field in this repo declares `max <= u16::MAX`,
        // so this cast never truncates.
        self.u16(bytes.len() as u16);
        self.out.extend_from_slice(bytes);
        Ok(())
    }}

    fn bytes_u32(
        &mut self,
        field: &'static str,
        max: usize,
        value: &[u8],
    ) -> Result<(), {error_ident}> {{
        if value.len() > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: value.len(),
                max,
            }});
        }}
        self.u32(value.len() as u32);
        self.out.extend_from_slice(value);
        Ok(())
    }}

    fn count_u32(
        &mut self,
        field: &'static str,
        max: usize,
        count: usize,
    ) -> Result<(), {error_ident}> {{
        if count > max {{
            return Err({error_ident}::FieldTooLong {{
                field,
                len: count,
                max,
            }});
        }}
        self.u32(count as u32);
        Ok(())
    }}
}}

"#
    );
}

fn write_self_contained_error(out: &mut String, error_ident: &str, schema: &Schema) {
    let _ = writeln!(
        out,
        "/// Decode/encode errors for `{}` (contract §2 rule 9). Self-contained: this schema's",
        schema.name
    );
    let _ = writeln!(
        out,
        "/// `error_type` directive is `\"self\"`, so this enum is generated here rather than"
    );
    let _ = writeln!(out, "/// reused from an existing hand-written type.");
    let _ = writeln!(
        out,
        "#[derive(Clone, PartialEq, Eq, Debug, thiserror::Error)]"
    );
    let _ = writeln!(out, "#[non_exhaustive]");
    let _ = writeln!(out, "pub enum {error_ident} {{");

    let _ = writeln!(
        out,
        "    /// Fewer bytes remained than this field needs (contract §2 rule 9)."
    );
    let _ = writeln!(
        out,
        "    #[error(\"unexpected end at offset {{offset}}: needed {{needed}} bytes, {{available}} available\")]"
    );
    let _ = writeln!(out, "    UnexpectedEnd {{");
    let _ = writeln!(out, "        /// Byte offset the read started at.");
    let _ = writeln!(out, "        offset: usize,");
    let _ = writeln!(out, "        /// Bytes needed.");
    let _ = writeln!(out, "        needed: usize,");
    let _ = writeln!(out, "        /// Bytes actually remaining.");
    let _ = writeln!(out, "        available: usize,");
    let _ = writeln!(out, "    }},");

    let _ = writeln!(
        out,
        "    /// Bytes remained after decoding a complete value (contract §13 \"keine Rest-Bytes\")."
    );
    let _ = writeln!(
        out,
        "    #[error(\"{{extra}} trailing byte(s) after a complete value\")]"
    );
    let _ = writeln!(out, "    TrailingBytes {{");
    let _ = writeln!(out, "        /// Byte count left over.");
    let _ = writeln!(out, "        extra: usize,");
    let _ = writeln!(out, "    }},");

    let _ = writeln!(out, "    /// A string field was not valid UTF-8.");
    let _ = writeln!(
        out,
        "    #[error(\"field {{field:?}} is not valid UTF-8\")]"
    );
    let _ = writeln!(out, "    InvalidUtf8 {{");
    let _ = writeln!(out, "        /// Field name.");
    let _ = writeln!(out, "        field: &'static str,");
    let _ = writeln!(out, "    }},");

    let _ = writeln!(
        out,
        "    /// A length or count exceeded the field's documented maximum."
    );
    let _ = writeln!(
        out,
        "    #[error(\"field {{field:?}} has length {{len}}, exceeding the {{max}}-byte/element limit\")]"
    );
    let _ = writeln!(out, "    FieldTooLong {{");
    let _ = writeln!(out, "        /// Field name.");
    let _ = writeln!(out, "        field: &'static str,");
    let _ = writeln!(out, "        /// Declared length or count.");
    let _ = writeln!(out, "        len: usize,");
    let _ = writeln!(out, "        /// Maximum allowed.");
    let _ = writeln!(out, "        max: usize,");
    let _ = writeln!(out, "    }},");

    let _ = writeln!(
        out,
        "    /// An enum or `bool`/`Option` tag byte matched no known value."
    );
    let _ = writeln!(
        out,
        "    #[error(\"field {{field:?}} has invalid value {{value}}\")]"
    );
    let _ = writeln!(out, "    InvalidEnum {{");
    let _ = writeln!(out, "        /// Field name.");
    let _ = writeln!(out, "        field: &'static str,");
    let _ = writeln!(out, "        /// Raw wire value.");
    let _ = writeln!(out, "        value: u32,");
    let _ = writeln!(out, "    }},");

    let _ = writeln!(out, "}}");
    out.push('\n');
}

fn write_enum(out: &mut String, def: &EnumDef) -> Result<(), String> {
    write_doc(out, "", &def.doc);
    if def.non_exhaustive {
        let _ = writeln!(out, "#[non_exhaustive]");
    }
    let _ = writeln!(out, "#[derive(Clone, Copy, PartialEq, Eq, Debug)]");
    let _ = writeln!(out, "pub enum {} {{", def.name);
    for variant in &def.variants {
        write_doc(out, "    ", &variant.doc);
        let _ = writeln!(out, "    {} = {},", variant.name, variant.value);
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
    Ok(())
}

fn write_struct(
    out: &mut String,
    def: &StructDef,
    schema: &Schema,
    error_ident: &str,
) -> Result<(), String> {
    write_doc(out, "", &def.doc);
    if def.growable {
        let _ = writeln!(out, "#[non_exhaustive]");
        let _ = writeln!(out, "#[derive(Clone, Default, PartialEq, Debug)]");
    } else {
        let _ = writeln!(out, "#[derive(Clone, PartialEq, Debug)]");
    }
    let _ = writeln!(out, "pub struct {} {{", def.name);
    for field in &def.fields {
        write_doc(out, "    ", &field.doc);
        let _ = writeln!(out, "    pub {}: {},", field.name, rust_type(&field.ty));
    }
    let _ = writeln!(out, "}}");
    out.push('\n');

    let _ = writeln!(out, "impl {} {{", def.name);
    let _ = writeln!(
        out,
        "    /// Encodes this payload (contract §2 rule 9): fails with `FieldTooLong` for the"
    );
    let _ = writeln!(
        out,
        "    /// first field whose length or count exceeds its declared maximum."
    );
    let _ = writeln!(
        out,
        "    pub fn encode(&self, out: &mut Vec<u8>) -> Result<(), {error_ident}> {{"
    );
    let _ = writeln!(out, "        let mut writer = Writer::new(out);");
    for field in &def.fields {
        let expr = format!("self.{}", field.name);
        let ctx = FieldCtx {
            field: &field.name,
            schema,
            error_ident,
        };
        write_encode(out, "        ", &expr, false, &field.ty, &ctx)?;
    }
    let _ = writeln!(out, "        Ok(())");
    let _ = writeln!(out, "    }}");
    out.push('\n');

    let _ = writeln!(
        out,
        "    /// Decodes this payload from exactly `bytes`: [`{error_ident}::TrailingBytes`] if"
    );
    let _ = writeln!(out, "    /// any byte is left over (contract §13).");
    let _ = writeln!(
        out,
        "    pub fn decode(bytes: &[u8]) -> Result<Self, {error_ident}> {{"
    );
    let _ = writeln!(out, "        let mut reader = Reader::new(bytes);");
    let _ = writeln!(out, "        let value = Self::decode_from(&mut reader)?;");
    let _ = writeln!(out, "        reader.finish()?;");
    let _ = writeln!(out, "        Ok(value)");
    let _ = writeln!(out, "    }}");
    out.push('\n');

    let _ = writeln!(
        out,
        "    /// Decodes this payload from `reader`, leaving the read head after its last byte"
    );
    let _ = writeln!(
        out,
        "    /// and any trailing bytes unconsumed (used when nested inside a `vec`/`option`;"
    );
    let _ = writeln!(
        out,
        "    /// only the outermost [`Self::decode`] enforces \"no trailing bytes\")."
    );
    let _ = writeln!(
        out,
        "    fn decode_from(reader: &mut Reader<'_>) -> Result<Self, {error_ident}> {{"
    );
    let mut field_names = Vec::with_capacity(def.fields.len());
    for field in &def.fields {
        let expr = decode_expr(&field.ty, &field.name, schema, error_ident)?;
        let _ = writeln!(out, "        let {} = {};", field.name, expr);
        field_names.push(field.name.clone());
    }
    let _ = writeln!(out, "        Ok(Self {{ {} }})", field_names.join(", "));
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out.push('\n');
    Ok(())
}

fn rust_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::U8 => "u8".to_owned(),
        TypeRef::U16 => "u16".to_owned(),
        TypeRef::U32 => "u32".to_owned(),
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => "u64".to_owned(),
        TypeRef::F32 => "f32".to_owned(),
        TypeRef::Bool => "bool".to_owned(),
        TypeRef::Str { .. } | TypeRef::Str16 { .. } => "String".to_owned(),
        TypeRef::Bytes { .. } => "Vec<u8>".to_owned(),
        TypeRef::Vec { elem, .. } | TypeRef::VecUsing { elem, .. } => {
            format!("Vec<{}>", rust_type(elem))
        }
        TypeRef::Option(inner) => format!("Option<{}>", rust_type(inner)),
        TypeRef::Array { elem, len } => format!("[{}; {len}]", rust_type(elem)),
        TypeRef::Named(name) => name.clone(),
    }
}

enum Resolved<'a> {
    Enum(&'a EnumDef),
    Struct(&'a StructDef),
}

fn resolve_named<'a>(schema: &'a Schema, name: &str) -> Result<Resolved<'a>, String> {
    for item in &schema.items {
        match item {
            Item::Enum(e) if e.name == name => return Ok(Resolved::Enum(e)),
            Item::Struct(s) if s.name == name => return Ok(Resolved::Struct(s)),
            _ => {}
        }
    }
    Err(format!(
        "type {name:?} is not declared in schema {:?}",
        schema.name
    ))
}

/// The parts of a field's context that stay the same across a `write_encode`/`decode_expr`
/// recursion (only `expr`/`is_ref`/`ty` change per call): bundled into one struct so the two
/// functions stay under clippy's argument-count limit instead of threading three more positional
/// parameters through every recursive call.
struct FieldCtx<'a> {
    /// The schema field's own name, for error messages (`FieldTooLong`, `InvalidEnum`, ...) —
    /// stays the field's name even while recursing into a `Vec`/`Option` element, since the
    /// contract reports errors per *field*, not per array element.
    field: &'a str,
    /// The schema this field's type is declared in, for resolving [`TypeRef::Named`].
    schema: &'a Schema,
    /// The schema's error type identifier (see [`error_type_ident`]).
    error_ident: &'a str,
}

/// Appends the Rust statement(s) that encode `expr` (a value of type `ty`) via `writer`.
///
/// `is_ref` says whether `expr` already denotes a reference to the value (e.g. a `Vec` loop
/// variable, or the bound name inside an `Option`'s `Some` arm) as opposed to an owned place
/// expression such as `self.field` — the two need different call syntax for the same field type
/// (e.g. `writer.array(&self.token)` vs. `writer.array(value)`), which this flag threads through
/// the recursion instead of trying to infer it from `expr`'s text.
fn write_encode(
    out: &mut String,
    indent: &str,
    expr: &str,
    is_ref: bool,
    ty: &TypeRef,
    ctx: &FieldCtx<'_>,
) -> Result<(), String> {
    let field = ctx.field;
    let schema = ctx.schema;
    let error_ident = ctx.error_ident;
    let deref = if is_ref { "*" } else { "" };
    let amp = if is_ref { "" } else { "&" };
    match ty {
        TypeRef::U8 => {
            let _ = writeln!(out, "{indent}writer.u8({deref}{expr});");
        }
        TypeRef::U16 => {
            let _ = writeln!(out, "{indent}writer.u16({deref}{expr});");
        }
        TypeRef::U32 => {
            let _ = writeln!(out, "{indent}writer.u32({deref}{expr});");
        }
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => {
            let _ = writeln!(out, "{indent}writer.u64({deref}{expr});");
        }
        TypeRef::F32 => {
            let _ = writeln!(out, "{indent}writer.f32({deref}{expr});");
        }
        TypeRef::Bool => {
            let _ = writeln!(out, "{indent}writer.bool({deref}{expr});");
        }
        TypeRef::Str { max } => {
            let _ = writeln!(
                out,
                "{indent}writer.str_u32({field:?}, {max}, {amp}{expr})?;"
            );
        }
        TypeRef::Str16 { max } => {
            let _ = writeln!(
                out,
                "{indent}writer.str_u16({field:?}, {max}, {amp}{expr})?;"
            );
        }
        TypeRef::Bytes { max } => {
            let _ = writeln!(
                out,
                "{indent}writer.bytes_u32({field:?}, {max}, {amp}{expr})?;"
            );
        }
        TypeRef::Array { elem, .. } => match **elem {
            TypeRef::U8 => {
                let _ = writeln!(out, "{indent}writer.array({amp}{expr});");
            }
            TypeRef::F32 => {
                let _ = writeln!(out, "{indent}writer.array_f32({amp}{expr});");
            }
            _ => return Err("array element type not supported by the Rust emitter".to_owned()),
        },
        TypeRef::Option(inner) => {
            let _ = writeln!(out, "{indent}match &{expr} {{");
            let _ = writeln!(out, "{indent}    Some(value) => {{");
            let _ = writeln!(out, "{indent}        writer.option_tag(true);");
            match &**inner {
                TypeRef::Array { elem, .. } => match **elem {
                    TypeRef::U8 => {
                        let _ = writeln!(out, "{indent}        writer.array(value);");
                    }
                    TypeRef::F32 => {
                        let _ = writeln!(out, "{indent}        writer.array_f32(value);");
                    }
                    _ => {
                        return Err(
                            "array element type not supported by the Rust emitter".to_owned()
                        );
                    }
                },
                TypeRef::Named(name) => match resolve_named(schema, name)? {
                    Resolved::Struct(_) => {
                        let _ = writeln!(out, "{indent}        value.encode(writer.out)?;");
                    }
                    Resolved::Enum(e) => {
                        let cast = match e.width {
                            EnumWidth::U8 => "u8",
                            EnumWidth::U16 => "u16",
                        };
                        let _ = writeln!(out, "{indent}        writer.{cast}(*value as {cast});");
                    }
                },
                _ => write_encode(out, &format!("{indent}        "), "value", true, inner, ctx)?,
            }
            let _ = writeln!(out, "{indent}    }}");
            let _ = writeln!(out, "{indent}    None => writer.option_tag(false),");
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::Vec { max, elem } => {
            let _ = writeln!(
                out,
                "{indent}writer.count_u32({field:?}, {max}, {expr}.len())?;"
            );
            let _ = writeln!(out, "{indent}for item in {amp}{expr} {{");
            write_encode(out, &format!("{indent}    "), "item", true, elem, ctx)?;
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::VecUsing { max, elem, .. } => {
            // No count is written here: the wire count is an earlier field's own value
            // (contract §12's manifest reuses `entry_count`), already encoded by its own field.
            // The length is still checked against `max` before allocating anything downstream,
            // exactly like `Vec` (contract §2 rule 9); only the wire representation differs.
            let _ = writeln!(out, "{indent}if {expr}.len() > {max} {{");
            let _ = writeln!(
                out,
                "{indent}    return Err({error_ident}::FieldTooLong {{ field: {field:?}, len: {expr}.len(), max: {max} }});"
            );
            let _ = writeln!(out, "{indent}}}");
            let _ = writeln!(out, "{indent}for item in {amp}{expr} {{");
            write_encode(out, &format!("{indent}    "), "item", true, elem, ctx)?;
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Struct(_) => {
                let _ = writeln!(out, "{indent}{expr}.encode(writer.out)?;");
            }
            Resolved::Enum(e) => {
                let cast = match e.width {
                    EnumWidth::U8 => "u8",
                    EnumWidth::U16 => "u16",
                };
                let _ = writeln!(out, "{indent}writer.{cast}({deref}{expr} as {cast});");
            }
        },
    }
    Ok(())
}

/// Returns a Rust expression (a single call or a `{{ ... }}` block, always ending in a value of
/// `ty`'s Rust type) that decodes one field from `reader`, using `?` internally to propagate a
/// decode error out of the enclosing `decode_from` function. `error_ident` is the schema's own
/// error type name (see [`error_type_ident`]), needed only for an enum field without a `fallback`
/// variant, whose default arm must construct an `InvalidEnum` value of that exact type.
fn decode_expr(
    ty: &TypeRef,
    field: &str,
    schema: &Schema,
    error_ident: &str,
) -> Result<String, String> {
    Ok(match ty {
        TypeRef::U8 => "reader.u8()?".to_owned(),
        TypeRef::U16 => "reader.u16()?".to_owned(),
        TypeRef::U32 => "reader.u32()?".to_owned(),
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => "reader.u64()?".to_owned(),
        TypeRef::F32 => "reader.f32()?".to_owned(),
        TypeRef::Bool => format!("reader.bool({field:?})?"),
        TypeRef::Str { max } => format!("reader.str_u32({field:?}, {max})?"),
        TypeRef::Str16 { max } => format!("reader.str_u16({field:?}, {max})?"),
        TypeRef::Bytes { max } => format!("reader.bytes_u32({field:?}, {max})?"),
        TypeRef::Array { elem, len } => match **elem {
            TypeRef::U8 => format!("reader.array::<{len}>()?"),
            TypeRef::F32 => format!("reader.array_f32::<{len}>()?"),
            _ => return Err("array element type not supported by the Rust emitter".to_owned()),
        },
        TypeRef::Option(inner) => {
            let inner_expr = decode_expr(inner, field, schema, error_ident)?;
            format!("if reader.option_tag({field:?})? {{ Some({inner_expr}) }} else {{ None }}")
        }
        TypeRef::Vec { max, elem } => {
            let elem_expr = decode_expr(elem, field, schema, error_ident)?;
            format!(
                "{{ let count = reader.count_u32({field:?}, {max})?; let mut items = Vec::with_capacity(count); for _ in 0..count {{ items.push({elem_expr}); }} items }}"
            )
        }
        TypeRef::VecUsing {
            count_field,
            max,
            elem,
        } => {
            // `count_field` names an earlier field of this same struct (checked by
            // `crate::parser::validate`), whose decoded value is already bound to a local
            // variable of that name at this point in `decode_from` — no count is read from the
            // wire here (contract §12's manifest reuses `entry_count`), but the value is still
            // checked against `max` before allocating, exactly like `Vec` (contract §2 rule 9).
            let elem_expr = decode_expr(elem, field, schema, error_ident)?;
            format!(
                "{{ let count = {count_field} as usize; if count > {max} {{ return Err({error_ident}::FieldTooLong {{ field: {field:?}, len: count, max: {max} }}); }} let mut items = Vec::with_capacity(count); for _ in 0..count {{ items.push({elem_expr}); }} items }}"
            )
        }
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Struct(s) => format!("{}::decode_from(reader)?", s.name),
            Resolved::Enum(e) => {
                let read = match e.width {
                    EnumWidth::U8 => "reader.u8()?".to_owned(),
                    EnumWidth::U16 => "reader.u16()?".to_owned(),
                };
                let mut arms = String::new();
                for variant in &e.variants {
                    let _ = write!(arms, "{} => {}::{}, ", variant.value, e.name, variant.name);
                }
                let default_arm = match &e.fallback {
                    Some(fallback) => format!("_ => {}::{fallback},", e.name),
                    None => format!(
                        "other => return Err({error_ident}::InvalidEnum {{ field: {field:?}, value: u32::from(other) }}),"
                    ),
                };
                format!("{{ match {read} {{ {arms}{default_arm} }} }}")
            }
        },
    })
}

fn write_catalogue(out: &mut String, schema: &Schema) {
    let _ = writeln!(
        out,
        "/// Message catalogue metadata (contract §13 \"Nachrichtenkatalog\"): id, direction and"
    );
    let _ = writeln!(
        out,
        "/// payload type. Building the actual dispatch (`Message` enum, `to_frame`/`from_frame`,"
    );
    let _ = writeln!(
        out,
        "/// the handshake) is Plan-0002 WP8.2, not this module; these constants exist so that"
    );
    let _ = writeln!(
        out,
        "/// work can read the catalogue from the same generated source as the payload types"
    );
    let _ = writeln!(
        out,
        "/// instead of re-copying it from the contract. Plain `u16` rather than"
    );
    let _ = writeln!(
        out,
        "/// `grimoire_debug::MessageId` on purpose: this file has no dependency on any"
    );
    let _ = writeln!(out, "/// particular crate's own wrapper type.");
    let _ = writeln!(out, "pub mod catalogue {{");
    out.push('\n');
    for message in &schema.messages {
        let mut doc = vec![format!(
            "`{}` payload, direction {}.",
            message.payload,
            message.direction.contract_label()
        )];
        doc.extend(message.doc.iter().cloned());
        write_doc(out, "    ", &doc);
        let _ = writeln!(
            out,
            "    pub const {}: u16 = {:#06x};",
            screaming_snake_case(&message.name),
            message.id
        );
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
}

fn screaming_snake_case(pascal: &str) -> String {
    let mut out = String::new();
    for (i, c) in pascal.chars().enumerate() {
        if c.is_uppercase() && i != 0 {
            out.push('_');
        }
        out.extend(c.to_uppercase());
    }
    out
}
