//! Docs emitter (project ADR-0011): turns a [`Schema`] into a Markdown field-table page for
//! `docs/formats/` (contract §2 rule 10 requires one such document per binary format; P-9 put
//! that document in this, the owning, repository).
//!
//! Output is plain Markdown with no external tool dependency (no `mdformat`/`prettier` pass in
//! CI), so determinism is entirely this module's responsibility: field order always follows
//! [`Schema::items`]/[`crate::ir::StructDef::fields`] (source order, never re-sorted), and nothing
//! here reads the clock, an environment variable or a tool version.

use crate::ir::{Item, MessageEntry, Schema, TypeRef};
use std::fmt::Write as _;

/// Renders `schema` as a complete Markdown page.
#[must_use]
pub fn emit(schema: &Schema) -> String {
    let mut out = String::new();

    let _ = writeln!(
        out,
        "<!-- @generated by grimoire_schemagen from {}. -->",
        schema.source_path
    );
    let _ = writeln!(
        out,
        "<!-- `cargo run -p grimoire_schemagen -- generate` regenerates this file; -->"
    );
    let _ = writeln!(
        out,
        "<!-- .github/scripts/check-schemagen-drift.sh fails CI if that would change it. -->"
    );
    out.push('\n');
    let _ = writeln!(out, "# {}", title_case(&schema.name));
    out.push('\n');
    if !schema.doc.is_empty() {
        for line in &schema.doc {
            let _ = writeln!(out, "{line}");
        }
        out.push('\n');
    }
    let _ = writeln!(out, "Format version **{}**.", schema.version);
    out.push('\n');
    let _ = writeln!(
        out,
        "This page is generated from `{}` by `grimoire_schemagen` (project ADR-0011); the",
        schema.source_path
    );
    let _ = writeln!(
        out,
        "generated Rust types live next to the crate that owns this format. Frame/pack framing"
    );
    let _ = writeln!(
        out,
        "logic (length prefixes, header, handshake) is documented in the engine contract"
    );
    let _ = writeln!(
        out,
        "(`docs/architektur/crate-vertraege.md`), not repeated here."
    );
    out.push('\n');

    if !schema.messages.is_empty() {
        write_catalogue_table(&mut out, &schema.messages);
    }

    for item in &schema.items {
        match item {
            Item::Enum(e) => {
                let _ = writeln!(out, "## `{}` (enum, {})", e.name, enum_width_label(e.width));
                out.push('\n');
                if !e.doc.is_empty() {
                    for line in &e.doc {
                        let _ = writeln!(out, "{line}");
                    }
                    out.push('\n');
                }
                if e.non_exhaustive {
                    let note = match &e.fallback {
                        Some(fallback) => format!(
                            "Growable (`#[non_exhaustive]`); an unrecognised wire value decodes as `{fallback}`."
                        ),
                        None => "Growable (`#[non_exhaustive]`).".to_owned(),
                    };
                    let _ = writeln!(out, "{note}");
                    out.push('\n');
                }
                let _ = writeln!(out, "| Value | Variant | Description |");
                let _ = writeln!(out, "|-------|---------|-------------|");
                for variant in &e.variants {
                    let _ = writeln!(
                        out,
                        "| {} | `{}` | {} |",
                        variant.value,
                        variant.name,
                        join_doc(&variant.doc)
                    );
                }
                out.push('\n');
            }
            Item::Struct(s) => {
                let _ = writeln!(out, "## `{}` (struct)", s.name);
                out.push('\n');
                if !s.doc.is_empty() {
                    for line in &s.doc {
                        let _ = writeln!(out, "{line}");
                    }
                    out.push('\n');
                }
                if s.growable {
                    let _ = writeln!(
                        out,
                        "Growable (`#[non_exhaustive]`, built via `Default` and field assignment)."
                    );
                    out.push('\n');
                }
                let _ = writeln!(out, "| Field | Wire type | Description |");
                let _ = writeln!(out, "|-------|-----------|-------------|");
                for field in &s.fields {
                    let _ = writeln!(
                        out,
                        "| `{}` | {} | {} |",
                        field.name,
                        describe_type(&field.ty),
                        join_doc(&field.doc)
                    );
                }
                out.push('\n');
            }
        }
    }

    out
}

fn write_catalogue_table(out: &mut String, messages: &[MessageEntry]) {
    let _ = writeln!(out, "## Message catalogue");
    out.push('\n');
    let _ = writeln!(out, "| ID | Message | Direction | Payload | Description |");
    let _ = writeln!(out, "|----|---------|-----------|---------|-------------|");
    for message in messages {
        let _ = writeln!(
            out,
            "| `{:#06x}` | `{}` | {} | [`{}`](#{}) | {} |",
            message.id,
            message.name,
            message.direction.contract_label(),
            message.payload,
            anchor(&message.payload),
            join_doc(&message.doc)
        );
    }
    out.push('\n');
}

/// Joins doc-comment lines into a single Markdown table cell (a literal `<br>` between lines
/// since GitHub-flavoured Markdown tables cannot contain a real newline inside a cell).
fn join_doc(doc: &[String]) -> String {
    if doc.is_empty() {
        return String::new();
    }
    doc.join("<br>").replace('|', "\\|")
}

fn describe_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::U8 => "u8".to_owned(),
        TypeRef::U16 => "u16".to_owned(),
        TypeRef::U32 => "u32".to_owned(),
        TypeRef::U64 => "u64".to_owned(),
        TypeRef::Hash64 => "hash64".to_owned(),
        TypeRef::Id64 => "id64".to_owned(),
        TypeRef::F32 => "f32".to_owned(),
        TypeRef::Bool => "bool".to_owned(),
        TypeRef::Str { max } => format!("Str≤{max}"),
        TypeRef::Str16 { max } => format!("Str16≤{max}"),
        TypeRef::Bytes { max } => format!("Bytes≤{max}"),
        TypeRef::Vec { max, elem } => format!("Vec≤{max}<{}>", describe_type(elem)),
        TypeRef::VecUsing {
            count_field,
            max,
            elem,
        } => format!(
            "Vec≤{max}<{}> (count = `{count_field}`, no separate wire count)",
            describe_type(elem)
        ),
        TypeRef::Option(inner) => format!("Option<{}>", describe_type(inner)),
        TypeRef::Array { elem, len } => format!("[{}; {len}]", describe_type(elem)),
        TypeRef::Named(name) => format!("[`{name}`](#{})", anchor(name)),
    }
}

/// GitHub's Markdown-heading-to-anchor rule for the simple, all-ASCII identifiers used in this
/// repo's schemas: lowercase, and every non-alphanumeric character becomes `-` (our headings are
/// of the form `` `Name` (struct) ``/`` `Name` (enum, u8) ``, so the leading backtick becomes part
/// of the anchor exactly like GitHub renders it).
fn anchor(name: &str) -> String {
    name.to_lowercase()
}

fn enum_width_label(width: crate::ir::EnumWidth) -> &'static str {
    match width {
        crate::ir::EnumWidth::U8 => "u8",
        crate::ir::EnumWidth::U16 => "u16",
    }
}

fn title_case(snake: &str) -> String {
    snake
        .split(['_', '-'])
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    #[test]
    fn emits_a_table_per_struct_and_enum() {
        let schema = parse(
            r#"
                schema "example"
                version 3
                error_type "self"

                enum PeerRole : u8 {
                    Tool = 0 "Tool side."
                    Engine = 1 "Engine side."
                }

                struct Hello {
                    role: PeerRole "The role."
                    token: [u8; 32] "Token."
                }

                message Hello = 1 dir both payload Hello "Handshake."
            "#,
        )
        .expect("schema should parse");
        let markdown = emit(&schema);
        assert!(markdown.contains("# Example"));
        assert!(markdown.contains("Format version **3**"));
        assert!(markdown.contains("## `PeerRole` (enum, u8)"));
        assert!(markdown.contains("## `Hello` (struct)"));
        assert!(markdown.contains("[`PeerRole`](#peerrole)"));
        assert!(markdown.contains("[u8; 32]"));
        assert!(markdown.contains("## Message catalogue"));
        assert!(markdown.contains("`0x0001`"));
    }
}
