//! C# emitter (project ADR-0011, Plan-0002 WP9.1): turns a [`Schema`] into one checked-in `.cs`
//! file for the C# tooling suite under `tools/` (PO decision P-1), next to the Rust emitter and
//! from the same IR, so both languages read and write the same bytes from one source.
//!
//! The output contains, per schema:
//!
//! - one `enum` per [`EnumDef`] with the declared wire width as its underlying type;
//! - one `sealed class` per [`StructDef`] with settable properties, value equality and an
//!   `Encode`/`EncodeTo`/`Decode`/`DecodeFrom` quartet that follows contract §2 rule 9: every
//!   length and count is checked against its maximum, and every count against the bytes remaining,
//!   before anything sized by it is allocated;
//! - a static class named after the schema with its format version and, for message schemas,
//!   the message catalogue (ids, directions, payload types).
//!
//! The generated code depends on a small hand-written runtime in the `Grimoire.Formats` assembly
//! (`WireReader`, `WireWriter`, `WireFormatException`, `WireEquality`, `MessageDirection`,
//! `MessageCatalogueEntry`), the counterpart of the private `Reader`/`Writer` the Rust emitter
//! writes into every file. Decoding throws only `WireFormatException` for malformed input.
//!
//! Like the Rust emitter, the output depends only on the IR, never embeds a timestamp, tool
//! version or absolute path, uses `\n` line endings and is written already formatted: the drift
//! check compares it byte for byte, without a formatter pass.

use crate::ir::{EnumDef, EnumWidth, Item, Schema, StructDef, TypeRef};
use std::fmt::Write as _;

/// Renders `schema` as a complete C# source file in `namespace`.
///
/// # Errors
/// Returns an error if a [`TypeRef::Named`] cannot be resolved against `schema.items`, if a
/// [`TypeRef::VecUsing`] names a count field that is not an earlier unsigned integer field of the
/// same struct, or if a fixed-size array uses an element type other than `u8` or `f32` (the only
/// two the contract uses; the Rust emitter has the same restriction).
pub fn emit(schema: &Schema, namespace: &str) -> Result<String, String> {
    let mut out = String::new();
    write_header(&mut out, schema, namespace);

    for item in &schema.items {
        match item {
            Item::Enum(def) => write_enum(&mut out, def),
            Item::Struct(def) => write_struct(&mut out, def, schema)?,
        }
    }
    write_schema_class(&mut out, schema);

    // Exactly one trailing newline, whatever the last writer left.
    while out.ends_with("\n\n") {
        out.pop();
    }
    Ok(out)
}

fn write_header(out: &mut String, schema: &Schema, namespace: &str) {
    let _ = writeln!(out, "// <auto-generated>");
    let _ = writeln!(
        out,
        "// Generated by grimoire_schemagen from {}. Do not edit by hand:",
        schema.source_path
    );
    let _ = writeln!(
        out,
        "// `cargo run -p grimoire_schemagen -- generate` regenerates this file, and"
    );
    let _ = writeln!(
        out,
        "// .github/scripts/check-schemagen-drift.sh fails CI if that would change it."
    );
    let _ = writeln!(out, "// </auto-generated>");
    out.push('\n');
    let _ = writeln!(out, "#nullable enable");
    out.push('\n');
    let _ = writeln!(out, "using System;");
    let _ = writeln!(out, "using System.Collections.Generic;");
    out.push('\n');
    let _ = writeln!(out, "namespace {namespace};");
    out.push('\n');
}

/// `snake_case` or `kebab-case` to `PascalCase`.
fn pascal_case(snake: &str) -> String {
    snake
        .split(['_', '-'])
        .filter(|s| !s.is_empty())
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

/// Local variable name for a decoded field: `_` plus `PascalCase`, so it can never collide with a
/// C# keyword or with a property name.
fn local_name(field: &str) -> String {
    format!("_{}", pascal_case(field))
}

/// Escapes XML special characters and turns Markdown code spans (`` `x` ``) into `<c>x</c>`.
fn xml_doc_text(line: &str) -> String {
    let mut out = String::new();
    let mut in_code = false;
    for c in line.chars() {
        match c {
            '`' => {
                out.push_str(if in_code { "</c>" } else { "<c>" });
                in_code = !in_code;
            }
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(c),
        }
    }
    if in_code {
        out.push_str("</c>");
    }
    out
}

fn write_summary(out: &mut String, indent: &str, doc: &[String]) {
    let _ = writeln!(out, "{indent}/// <summary>");
    if doc.is_empty() {
        // CS1591 (missing XML comment) is an error in the tools build, like `missing_docs` in the
        // engine: every public member this emitter writes carries something.
        let _ = writeln!(out, "{indent}/// (Undocumented in the schema source.)");
    }
    for line in doc {
        let _ = writeln!(out, "{indent}/// {}", xml_doc_text(line));
    }
    let _ = writeln!(out, "{indent}/// </summary>");
}

fn enum_underlying(width: EnumWidth) -> &'static str {
    match width {
        EnumWidth::U8 => "byte",
        EnumWidth::U16 => "ushort",
    }
}

fn write_enum(out: &mut String, def: &EnumDef) {
    let mut doc = def.doc.clone();
    if let Some(fallback) = &def.fallback {
        doc.push(format!(
            "A wire value that names no variant decodes as `{fallback}`."
        ));
    }
    write_summary(out, "", &doc);
    let _ = writeln!(
        out,
        "public enum {} : {}",
        def.name,
        enum_underlying(def.width)
    );
    let _ = writeln!(out, "{{");
    for variant in &def.variants {
        write_summary(out, "    ", &variant.doc);
        let _ = writeln!(out, "    {} = {},", variant.name, variant.value);
        out.push('\n');
    }
    if out.ends_with("\n\n") {
        out.pop();
    }
    let _ = writeln!(out, "}}");
    out.push('\n');
}

enum Resolved<'a> {
    Enum(&'a EnumDef),
    Struct(&'a StructDef),
}

fn resolve_named<'a>(schema: &'a Schema, name: &str) -> Result<Resolved<'a>, String> {
    for item in &schema.items {
        match item {
            Item::Enum(def) if def.name == name => return Ok(Resolved::Enum(def)),
            Item::Struct(def) if def.name == name => return Ok(Resolved::Struct(def)),
            _ => {}
        }
    }
    Err(format!("unresolved type reference `{name}`"))
}

/// The C# type of a field or element.
fn cs_type(ty: &TypeRef) -> Result<String, String> {
    Ok(match ty {
        TypeRef::U8 => "byte".to_owned(),
        TypeRef::U16 => "ushort".to_owned(),
        TypeRef::U32 => "uint".to_owned(),
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => "ulong".to_owned(),
        TypeRef::F32 => "float".to_owned(),
        TypeRef::Bool => "bool".to_owned(),
        TypeRef::Str { .. } | TypeRef::Str16 { .. } => "string".to_owned(),
        TypeRef::Bytes { .. } => "byte[]".to_owned(),
        TypeRef::Vec { elem, .. } | TypeRef::VecUsing { elem, .. } => {
            format!("List<{}>", cs_type(elem)?)
        }
        TypeRef::Option(inner) => format!("{}?", cs_type(inner)?),
        TypeRef::Array { elem, .. } => match **elem {
            TypeRef::U8 => "byte[]".to_owned(),
            TypeRef::F32 => "float[]".to_owned(),
            _ => return Err("array element type not supported by the C# emitter".to_owned()),
        },
        TypeRef::Named(name) => name.clone(),
    })
}

/// Initialiser for a property of type `ty`, so a freshly constructed value always encodes (empty
/// strings and collections, zero-filled fixed arrays, `null` for an absent option).
fn cs_default(ty: &TypeRef, schema: &Schema) -> Result<Option<String>, String> {
    Ok(match ty {
        TypeRef::Str { .. } | TypeRef::Str16 { .. } => Some("string.Empty".to_owned()),
        TypeRef::Bytes { .. } => Some("Array.Empty<byte>()".to_owned()),
        TypeRef::Vec { elem, .. } | TypeRef::VecUsing { elem, .. } => {
            Some(format!("new List<{}>()", cs_type(elem)?))
        }
        TypeRef::Array { elem, len } => match **elem {
            TypeRef::U8 => Some(format!("new byte[{len}]")),
            TypeRef::F32 => Some(format!("new float[{len}]")),
            _ => return Err("array element type not supported by the C# emitter".to_owned()),
        },
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Struct(_) => Some(format!("new {name}()")),
            Resolved::Enum(_) => None,
        },
        _ => None,
    })
}

/// Smallest number of bytes one value of `ty` occupies on the wire; a declared element count
/// times this is checked against the bytes remaining before a list is allocated.
fn min_wire_size(ty: &TypeRef, schema: &Schema) -> Result<u64, String> {
    Ok(match ty {
        TypeRef::U8 | TypeRef::Bool | TypeRef::Option(_) => 1,
        TypeRef::U16 | TypeRef::Str16 { .. } => 2,
        TypeRef::U32 | TypeRef::F32 | TypeRef::Str { .. } | TypeRef::Bytes { .. } => 4,
        TypeRef::Vec { .. } => 4,
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => 8,
        TypeRef::VecUsing { .. } => 0,
        TypeRef::Array { elem, len } => min_wire_size(elem, schema)? * u64::from(*len),
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Enum(def) => match def.width {
                EnumWidth::U8 => 1,
                EnumWidth::U16 => 2,
            },
            Resolved::Struct(def) => {
                let mut total = 0;
                for field in &def.fields {
                    total += min_wire_size(&field.ty, schema)?;
                }
                total
            }
        },
    })
}

fn write_struct(out: &mut String, def: &StructDef, schema: &Schema) -> Result<(), String> {
    let name = &def.name;
    write_summary(out, "", &def.doc);
    let _ = writeln!(out, "public sealed class {name} : IEquatable<{name}>");
    let _ = writeln!(out, "{{");

    for field in &def.fields {
        write_summary(out, "    ", &field.doc);
        let property = pascal_case(&field.name);
        let ty = cs_type(&field.ty)?;
        match cs_default(&field.ty, schema)? {
            Some(default) => {
                let _ = writeln!(
                    out,
                    "    public {ty} {property} {{ get; set; }} = {default};"
                );
            }
            None => {
                let _ = writeln!(out, "    public {ty} {property} {{ get; set; }}");
            }
        }
        out.push('\n');
    }

    // Encode.
    let _ = writeln!(out, "    /// <summary>");
    let _ = writeln!(
        out,
        "    /// Encodes this value into a new array (contract §2 rule 9)."
    );
    let _ = writeln!(out, "    /// </summary>");
    let _ = writeln!(
        out,
        "    /// <exception cref=\"WireFormatException\">A length or count exceeds its maximum.</exception>"
    );
    let _ = writeln!(out, "    public byte[] Encode()");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        var writer = new WireWriter();");
    let _ = writeln!(out, "        EncodeTo(writer);");
    let _ = writeln!(out, "        return writer.ToArray();");
    let _ = writeln!(out, "    }}");
    out.push('\n');
    let _ = writeln!(out, "    /// <summary>");
    let _ = writeln!(
        out,
        "    /// Appends this value to <paramref name=\"writer\"/> in wire order."
    );
    let _ = writeln!(out, "    /// </summary>");
    let _ = writeln!(
        out,
        "    /// <exception cref=\"WireFormatException\">A length or count exceeds its maximum.</exception>"
    );
    let _ = writeln!(out, "    public void EncodeTo(WireWriter writer)");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        ArgumentNullException.ThrowIfNull(writer);");
    for field in &def.fields {
        let property = pascal_case(&field.name);
        write_encode(
            out,
            "        ",
            &property,
            &field.ty,
            &field.name,
            def,
            schema,
        )?;
    }
    let _ = writeln!(out, "    }}");
    out.push('\n');

    // Decode.
    let _ = writeln!(out, "    /// <summary>");
    let _ = writeln!(
        out,
        "    /// Decodes a value from exactly <paramref name=\"bytes\"/>; left-over bytes are an error."
    );
    let _ = writeln!(out, "    /// </summary>");
    let _ = writeln!(
        out,
        "    /// <exception cref=\"WireFormatException\">The bytes are not a valid encoding.</exception>"
    );
    let _ = writeln!(
        out,
        "    public static {name} Decode(ReadOnlySpan<byte> bytes)"
    );
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        var reader = new WireReader(bytes);");
    let _ = writeln!(out, "        var value = DecodeFrom(ref reader);");
    let _ = writeln!(out, "        reader.Finish();");
    let _ = writeln!(out, "        return value;");
    let _ = writeln!(out, "    }}");
    out.push('\n');
    let _ = writeln!(out, "    /// <summary>");
    let _ = writeln!(
        out,
        "    /// Decodes a value from <paramref name=\"reader\"/>, leaving any bytes after it unread."
    );
    let _ = writeln!(out, "    /// </summary>");
    let _ = writeln!(
        out,
        "    /// <exception cref=\"WireFormatException\">The bytes are not a valid encoding.</exception>"
    );
    let _ = writeln!(
        out,
        "    public static {name} DecodeFrom(ref WireReader reader)"
    );
    let _ = writeln!(out, "    {{");
    for field in &def.fields {
        let local = local_name(&field.name);
        write_decode(out, "        ", &local, &field.ty, &field.name, def, schema)?;
    }
    let _ = writeln!(out, "        return new {name}");
    let _ = writeln!(out, "        {{");
    for field in &def.fields {
        let _ = writeln!(
            out,
            "            {} = {},",
            pascal_case(&field.name),
            local_name(&field.name)
        );
    }
    let _ = writeln!(out, "        }};");
    let _ = writeln!(out, "    }}");
    out.push('\n');

    write_equality(out, def)?;
    let _ = writeln!(out, "}}");
    out.push('\n');
    Ok(())
}

fn write_encode(
    out: &mut String,
    indent: &str,
    expr: &str,
    ty: &TypeRef,
    field: &str,
    def: &StructDef,
    schema: &Schema,
) -> Result<(), String> {
    match ty {
        TypeRef::U8 => {
            let _ = writeln!(out, "{indent}writer.U8({expr});");
        }
        TypeRef::U16 => {
            let _ = writeln!(out, "{indent}writer.U16({expr});");
        }
        TypeRef::U32 => {
            let _ = writeln!(out, "{indent}writer.U32({expr});");
        }
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => {
            let _ = writeln!(out, "{indent}writer.U64({expr});");
        }
        TypeRef::F32 => {
            let _ = writeln!(out, "{indent}writer.F32({expr});");
        }
        TypeRef::Bool => {
            let _ = writeln!(out, "{indent}writer.Bool({expr});");
        }
        TypeRef::Str { max } => {
            let _ = writeln!(out, "{indent}writer.StrU32(\"{field}\", {max}, {expr});");
        }
        TypeRef::Str16 { max } => {
            let _ = writeln!(out, "{indent}writer.StrU16(\"{field}\", {max}, {expr});");
        }
        TypeRef::Bytes { max } => {
            let _ = writeln!(out, "{indent}writer.BytesU32(\"{field}\", {max}, {expr});");
        }
        TypeRef::Array { elem, len } => match **elem {
            TypeRef::U8 => {
                let _ = writeln!(out, "{indent}writer.Bytes(\"{field}\", {len}, {expr});");
            }
            TypeRef::F32 => {
                let _ = writeln!(out, "{indent}writer.Floats(\"{field}\", {len}, {expr});");
            }
            _ => return Err("array element type not supported by the C# emitter".to_owned()),
        },
        TypeRef::Option(inner) => {
            let is_value_type = is_value_type(inner, schema)?;
            let _ = writeln!(out, "{indent}if ({expr} is null)");
            let _ = writeln!(out, "{indent}{{");
            let _ = writeln!(out, "{indent}    writer.OptionTag(false);");
            let _ = writeln!(out, "{indent}}}");
            let _ = writeln!(out, "{indent}else");
            let _ = writeln!(out, "{indent}{{");
            let _ = writeln!(out, "{indent}    writer.OptionTag(true);");
            let inner_expr = if is_value_type {
                format!("{expr}.Value")
            } else {
                expr.to_owned()
            };
            write_encode(
                out,
                &format!("{indent}    "),
                &inner_expr,
                inner,
                field,
                def,
                schema,
            )?;
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::Vec { max, elem } => {
            let _ = writeln!(out, "{indent}writer.Count(\"{field}\", {max}, {expr});");
            let item = format!("item{}", indent.len());
            let _ = writeln!(out, "{indent}foreach (var {item} in {expr})");
            let _ = writeln!(out, "{indent}{{");
            write_encode(
                out,
                &format!("{indent}    "),
                &item,
                elem,
                field,
                def,
                schema,
            )?;
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::VecUsing {
            count_field,
            max,
            elem,
        } => {
            let count_property = pascal_case(count_field);
            check_count_field(def, count_field)?;
            // The element count is not written here: it is the value of the earlier count field,
            // so the two must agree, or the encoder would write a corrupt manifest.
            let _ = writeln!(
                out,
                "{indent}writer.CountUsing(\"{field}\", \"{count_field}\", {max}, (ulong){count_property}, {expr});"
            );
            let item = format!("item{}", indent.len());
            let _ = writeln!(out, "{indent}foreach (var {item} in {expr})");
            let _ = writeln!(out, "{indent}{{");
            write_encode(
                out,
                &format!("{indent}    "),
                &item,
                elem,
                field,
                def,
                schema,
            )?;
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Struct(_) => {
                let _ = writeln!(out, "{indent}{expr}.EncodeTo(writer);");
            }
            Resolved::Enum(e) => {
                let _ = writeln!(
                    out,
                    "{indent}writer.{}(({}){expr});",
                    match e.width {
                        EnumWidth::U8 => "U8",
                        EnumWidth::U16 => "U16",
                    },
                    enum_underlying(e.width)
                );
            }
        },
    }
    Ok(())
}

/// Whether `ty` maps to a C# value type, whose `Option` is a `Nullable<T>` read through `.Value`.
fn is_value_type(ty: &TypeRef, schema: &Schema) -> Result<bool, String> {
    Ok(match ty {
        TypeRef::Str { .. }
        | TypeRef::Str16 { .. }
        | TypeRef::Bytes { .. }
        | TypeRef::Vec { .. }
        | TypeRef::VecUsing { .. }
        | TypeRef::Array { .. }
        | TypeRef::Option(_) => false,
        TypeRef::Named(name) => matches!(resolve_named(schema, name)?, Resolved::Enum(_)),
        _ => true,
    })
}

/// `count_field` must be an earlier unsigned integer field of `def`.
fn check_count_field(def: &StructDef, count_field: &str) -> Result<(), String> {
    match def.fields.iter().find(|field| field.name == count_field) {
        Some(field)
            if matches!(
                field.ty,
                TypeRef::U8 | TypeRef::U16 | TypeRef::U32 | TypeRef::U64
            ) =>
        {
            Ok(())
        }
        _ => Err(format!(
            "`vec_using` count field `{count_field}` of `{}` is not an unsigned integer field",
            def.name
        )),
    }
}

/// Writes statements that decode one value of `ty` into a new local named `target`. Helper locals
/// derive their names from `target`, which is unique per field and nesting level.
fn write_decode(
    out: &mut String,
    indent: &str,
    target: &str,
    ty: &TypeRef,
    field: &str,
    def: &StructDef,
    schema: &Schema,
) -> Result<(), String> {
    let declare = |out: &mut String, value: &str| {
        let _ = writeln!(out, "{indent}var {target} = {value};");
    };
    match ty {
        TypeRef::U8 => declare(out, "reader.U8()"),
        TypeRef::U16 => declare(out, "reader.U16()"),
        TypeRef::U32 => declare(out, "reader.U32()"),
        TypeRef::U64 | TypeRef::Hash64 | TypeRef::Id64 => declare(out, "reader.U64()"),
        TypeRef::F32 => declare(out, "reader.F32()"),
        TypeRef::Bool => declare(out, &format!("reader.Bool(\"{field}\")")),
        TypeRef::Str { max } => declare(out, &format!("reader.StrU32(\"{field}\", {max})")),
        TypeRef::Str16 { max } => declare(out, &format!("reader.StrU16(\"{field}\", {max})")),
        TypeRef::Bytes { max } => declare(out, &format!("reader.BytesU32(\"{field}\", {max})")),
        TypeRef::Array { elem, len } => match **elem {
            TypeRef::U8 => declare(out, &format!("reader.Bytes({len})")),
            TypeRef::F32 => declare(out, &format!("reader.Floats({len})")),
            _ => return Err("array element type not supported by the C# emitter".to_owned()),
        },
        TypeRef::Option(inner) => {
            let _ = writeln!(out, "{indent}{} {target} = null;", cs_type(ty)?);
            let _ = writeln!(out, "{indent}if (reader.OptionTag(\"{field}\"))");
            let _ = writeln!(out, "{indent}{{");
            let inner_target = format!("{target}Inner");
            write_decode(
                out,
                &format!("{indent}    "),
                &inner_target,
                inner,
                field,
                def,
                schema,
            )?;
            let _ = writeln!(out, "{indent}    {target} = {inner_target};");
            let _ = writeln!(out, "{indent}}}");
        }
        TypeRef::Vec { max, elem } => {
            let count = format!("{target}Count");
            let min = min_wire_size(elem, schema)?;
            let _ = writeln!(
                out,
                "{indent}var {count} = reader.Count(\"{field}\", {max}, {min});"
            );
            write_list_decode(out, indent, target, &count, elem, field, def, schema)?;
        }
        TypeRef::VecUsing {
            count_field,
            max,
            elem,
        } => {
            check_count_field(def, count_field)?;
            let count = format!("{target}Count");
            let min = min_wire_size(elem, schema)?;
            let _ = writeln!(
                out,
                "{indent}var {count} = reader.CountUsing(\"{field}\", {max}, (ulong){}, {min});",
                local_name(count_field)
            );
            write_list_decode(out, indent, target, &count, elem, field, def, schema)?;
        }
        TypeRef::Named(name) => match resolve_named(schema, name)? {
            Resolved::Struct(_) => declare(out, &format!("{name}.DecodeFrom(ref reader)")),
            Resolved::Enum(e) => {
                let raw = format!("{target}Raw");
                let read = match e.width {
                    EnumWidth::U8 => "reader.U8()",
                    EnumWidth::U16 => "reader.U16()",
                };
                let _ = writeln!(out, "{indent}var {raw} = {read};");
                let _ = writeln!(out, "{indent}var {target} = {raw} switch");
                let _ = writeln!(out, "{indent}{{");
                for variant in &e.variants {
                    let _ = writeln!(
                        out,
                        "{indent}    {} => {}.{},",
                        variant.value, e.name, variant.name
                    );
                }
                match &e.fallback {
                    Some(fallback) => {
                        let _ = writeln!(out, "{indent}    _ => {}.{fallback},", e.name);
                    }
                    None => {
                        let _ = writeln!(
                            out,
                            "{indent}    _ => throw WireFormatException.InvalidEnum(\"{field}\", {raw}),"
                        );
                    }
                }
                let _ = writeln!(out, "{indent}}};");
            }
        },
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn write_list_decode(
    out: &mut String,
    indent: &str,
    target: &str,
    count: &str,
    elem: &TypeRef,
    field: &str,
    def: &StructDef,
    schema: &Schema,
) -> Result<(), String> {
    let _ = writeln!(
        out,
        "{indent}var {target} = new List<{}>({count});",
        cs_type(elem)?
    );
    let index = format!("{target}Index");
    let _ = writeln!(
        out,
        "{indent}for (var {index} = 0; {index} < {count}; {index}++)"
    );
    let _ = writeln!(out, "{indent}{{");
    let element = format!("{target}Element");
    write_decode(
        out,
        &format!("{indent}    "),
        &element,
        elem,
        field,
        def,
        schema,
    )?;
    let _ = writeln!(out, "{indent}    {target}.Add({element});");
    let _ = writeln!(out, "{indent}}}");
    Ok(())
}

/// The C# expression comparing `left` and `right` of type `ty` for value equality.
fn equality_expr(ty: &TypeRef, left: &str, right: &str) -> Result<String, String> {
    Ok(match ty {
        TypeRef::F32 => format!("WireEquality.Float({left}, {right})"),
        TypeRef::Str { .. } | TypeRef::Str16 { .. } => {
            format!("string.Equals({left}, {right}, StringComparison.Ordinal)")
        }
        TypeRef::Bytes { .. } => format!("WireEquality.Bytes({left}, {right})"),
        TypeRef::Array { elem, .. } => match **elem {
            TypeRef::U8 => format!("WireEquality.Bytes({left}, {right})"),
            TypeRef::F32 => format!("WireEquality.Floats({left}, {right})"),
            _ => return Err("array element type not supported by the C# emitter".to_owned()),
        },
        TypeRef::Vec { .. } | TypeRef::VecUsing { .. } => {
            format!("WireEquality.Lists({left}, {right})")
        }
        TypeRef::Option(inner) => match **inner {
            TypeRef::F32 => format!("WireEquality.OptionalFloat({left}, {right})"),
            TypeRef::Array { .. }
            | TypeRef::Bytes { .. }
            | TypeRef::Vec { .. }
            | TypeRef::VecUsing { .. }
            | TypeRef::Str { .. }
            | TypeRef::Str16 { .. } => {
                let inner_eq = equality_expr(inner, left, right)?;
                format!("({left} is null ? {right} is null : {right} is not null && {inner_eq})")
            }
            _ => format!("Equals({left}, {right})"),
        },
        TypeRef::Named(_) => format!("Equals({left}, {right})"),
        _ => format!("{left} == {right}"),
    })
}

fn write_equality(out: &mut String, def: &StructDef) -> Result<(), String> {
    let name = &def.name;
    let _ = writeln!(out, "    /// <inheritdoc/>");
    let _ = writeln!(out, "    public bool Equals({name}? other)");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        if (other is null)");
    let _ = writeln!(out, "        {{");
    let _ = writeln!(out, "            return false;");
    let _ = writeln!(out, "        }}");
    out.push('\n');
    if def.fields.is_empty() {
        let _ = writeln!(out, "        return true;");
    } else {
        for (index, field) in def.fields.iter().enumerate() {
            let property = pascal_case(&field.name);
            let expr = equality_expr(&field.ty, &property, &format!("other.{property}"))?;
            let prefix = if index == 0 { "return " } else { "    && " };
            let suffix = if index + 1 == def.fields.len() {
                ";"
            } else {
                ""
            };
            let _ = writeln!(out, "        {prefix}{expr}{suffix}");
        }
    }
    let _ = writeln!(out, "    }}");
    out.push('\n');
    let _ = writeln!(out, "    /// <inheritdoc/>");
    let _ = writeln!(
        out,
        "    public override bool Equals(object? obj) => Equals(obj as {name});"
    );
    out.push('\n');
    let _ = writeln!(out, "    /// <inheritdoc/>");
    let _ = writeln!(out, "    public override int GetHashCode()");
    let _ = writeln!(out, "    {{");
    let _ = writeln!(out, "        var hash = new HashCode();");
    for field in &def.fields {
        let property = pascal_case(&field.name);
        let value = match &field.ty {
            TypeRef::Bytes { .. } | TypeRef::Array { .. } => format!("{property}?.Length ?? -1"),
            TypeRef::Vec { .. } | TypeRef::VecUsing { .. } => format!("{property}?.Count ?? -1"),
            TypeRef::Str { .. } | TypeRef::Str16 { .. } => {
                format!("{property}, StringComparer.Ordinal")
            }
            TypeRef::F32 => format!("BitConverter.SingleToInt32Bits({property})"),
            TypeRef::Option(inner) => match **inner {
                TypeRef::Array { .. } | TypeRef::Bytes { .. } => {
                    format!("{property}?.Length ?? -1")
                }
                TypeRef::Vec { .. } | TypeRef::VecUsing { .. } => {
                    format!("{property}?.Count ?? -1")
                }
                TypeRef::F32 => format!(
                    "{property} is null ? 0 : BitConverter.SingleToInt32Bits({property}.Value)"
                ),
                _ => format!("{property}?.GetHashCode() ?? 0"),
            },
            _ => property.clone(),
        };
        let _ = writeln!(out, "        hash.Add({value});");
    }
    let _ = writeln!(out, "        return hash.ToHashCode();");
    let _ = writeln!(out, "    }}");
    Ok(())
}

fn write_schema_class(out: &mut String, schema: &Schema) {
    let class = pascal_case(&schema.name);
    let mut doc = vec![format!("Schema `{}`.", schema.name)];
    doc.extend(schema.doc.iter().cloned());
    write_summary(out, "", &doc);
    let _ = writeln!(out, "public static class {class}");
    let _ = writeln!(out, "{{");
    write_summary(
        out,
        "    ",
        &["Format or protocol version the schema describes.".to_owned()],
    );
    let _ = writeln!(
        out,
        "    public const uint FormatVersion = {};",
        schema.version
    );

    if !schema.messages.is_empty() {
        out.push('\n');
        for message in &schema.messages {
            let mut doc = vec![format!(
                "Message id of `{}`, direction {}, payload `{}`.",
                message.name,
                message.direction.contract_label(),
                message.payload
            )];
            doc.extend(message.doc.iter().cloned());
            write_summary(out, "    ", &doc);
            let _ = writeln!(
                out,
                "    public const ushort {}Id = {:#06x};",
                message.name, message.id
            );
            out.push('\n');
        }
        write_summary(
            out,
            "    ",
            &["The message catalogue in id order of declaration.".to_owned()],
        );
        let _ = writeln!(
            out,
            "    public static IReadOnlyList<MessageCatalogueEntry> Catalogue {{ get; }} = new MessageCatalogueEntry[]"
        );
        let _ = writeln!(out, "    {{");
        for message in &schema.messages {
            let direction = match message.direction {
                crate::ir::Direction::ToolToEngine => "ToolToEngine",
                crate::ir::Direction::EngineToTool => "EngineToTool",
                crate::ir::Direction::Both => "Both",
            };
            let _ = writeln!(
                out,
                "        new({}Id, \"{}\", MessageDirection.{direction}, typeof({})),",
                message.name, message.name, message.payload
            );
        }
        let _ = writeln!(out, "    }};");
    }
    let _ = writeln!(out, "}}");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    fn example() -> Schema {
        let mut schema = parse(
            r#"
                schema "example_v1"
                version 3
                error_type "self"
                "An example <format> & more."

                doc "Which side."
                enum PeerRole : u8 {
                    Tool = 0 "Tool side."
                    Engine = 1 "Engine side."
                }

                doc "An error code."
                enum Code : u16 non_exhaustive fallback Other {
                    One = 1 "First."
                    Other = 2 "Anything else."
                }

                doc "A row."
                struct Row {
                    name: str(64) "The `name`."
                    value: u64 "The value."
                }

                doc "The payload."
                struct Hello growable {
                    role: PeerRole "The role."
                    code: Code "The code."
                    token: [u8; 32] "Token."
                    target: option([f32; 2]) "Optional target."
                    alpha: f32 "Alpha."
                    enabled: bool "Flag."
                    rows: vec(8) Row "Rows."
                    count: u32 "Path count."
                    paths: vec_using(count, 16) str16(255) "Paths."
                    blob: bytes(1024) "Blob."
                }

                message Hello = 0x0001 dir both payload Hello "Handshake."
            "#,
        )
        .expect("schema should parse");
        schema.source_path = "schema/example_v1.gschema".to_owned();
        schema
    }

    #[test]
    fn emits_types_codecs_and_the_catalogue() {
        let code = emit(&example(), "Grimoire.Formats.Example").expect("emits");
        assert!(code.starts_with("// <auto-generated>\n"));
        assert!(code.contains("from schema/example_v1.gschema."));
        assert!(code.contains("namespace Grimoire.Formats.Example;"));
        assert!(code.contains("public enum PeerRole : byte"));
        assert!(code.contains("public enum Code : ushort"));
        assert!(code.contains("A wire value that names no variant decodes as <c>Other</c>."));
        assert!(code.contains("public sealed class Hello : IEquatable<Hello>"));
        assert!(code.contains("public byte[] Token { get; set; } = new byte[32];"));
        assert!(code.contains("public float[]? Target { get; set; }"));
        assert!(code.contains("public List<Row> Rows { get; set; } = new List<Row>();"));
        assert!(code.contains("writer.StrU16(\"paths\", 255, item8);"));
        assert!(code.contains("writer.CountUsing(\"paths\", \"count\", 16, (ulong)Count, Paths);"));
        assert!(code.contains("var _RowsCount = reader.Count(\"rows\", 8, 12);"));
        assert!(
            code.contains("var _PathsCount = reader.CountUsing(\"paths\", 16, (ulong)_Count, 2);")
        );
        assert!(code.contains("_ => Code.Other,"));
        assert!(code.contains("_ => throw WireFormatException.InvalidEnum(\"role\", _RoleRaw),"));
        assert!(code.contains("public const ushort HelloId = 0x0001;"));
        assert!(code.contains("new(HelloId, \"Hello\", MessageDirection.Both, typeof(Hello)),"));
        assert!(code.contains("/// An example &lt;format&gt; &amp; more."));
        assert!(code.contains("/// The <c>name</c>."));
        assert!(code.ends_with("}\n"));
        assert!(!code.ends_with("\n\n"));
        assert!(!code.contains('\r'));
    }

    #[test]
    fn output_is_identical_on_every_run() {
        let schema = example();
        assert_eq!(
            emit(&schema, "Grimoire.Formats.Example"),
            emit(&schema, "Grimoire.Formats.Example")
        );
    }

    #[test]
    fn minimum_wire_sizes_follow_the_encoding() {
        let schema = example();
        assert_eq!(
            min_wire_size(&TypeRef::Named("Row".to_owned()), &schema),
            Ok(12)
        );
        assert_eq!(min_wire_size(&TypeRef::Str16 { max: 255 }, &schema), Ok(2));
        assert_eq!(
            min_wire_size(
                &TypeRef::Array {
                    elem: Box::new(TypeRef::F32),
                    len: 2
                },
                &schema
            ),
            Ok(8)
        );
        assert_eq!(
            min_wire_size(&TypeRef::Named("Code".to_owned()), &schema),
            Ok(2)
        );
    }

    #[test]
    fn unsupported_array_elements_are_an_error() {
        let mut schema = example();
        if let Some(Item::Struct(def)) = schema.items.last_mut() {
            def.fields[2].ty = TypeRef::Array {
                elem: Box::new(TypeRef::U64),
                len: 4,
            };
        }
        assert!(emit(&schema, "X").is_err());
    }

    #[test]
    fn xml_docs_escape_markup_and_close_open_code_spans() {
        assert_eq!(xml_doc_text("a < b"), "a &lt; b");
        assert_eq!(xml_doc_text("`x` and `y"), "<c>x</c> and <c>y</c>");
    }
}
