//! `grimoire_schemagen`: schema-description compiler (project ADR-0011, Plan-0002 WP8.1).
//!
//! Project ADR-0011 (accepted, option 2e) picked a small, project-specific schema description
//! language over an off-the-shelf binary-serialisation format because none of those match this
//! engine's already-frozen wire layouts (contract §12 pack manifest, §13 debug protocol) or
//! guarantee canonical bytes on both a Rust and a future C# writer; see the ADR for the full
//! comparison. This crate is that language's compiler: [`parser`] turns a `.gschema` source file
//! into the [`ir::Schema`] intermediate representation, and [`emit_rust`]/[`emit_docs`] each turn
//! an [`ir::Schema`] into their own output — a checked-in Rust module with `encode`/`decode`
//! functions that follow contract §2 rule 9, and a Markdown field-table page for `docs/formats/`
//! — without looking at the source text again. The [`ir`] module is deliberately the only thing
//! either emitter depends on, so a third emitter can be added next to these two without changing
//! the parser or either existing emitter; [`emit_csharp`] (Plan-0002 WP9.1) is that third emitter,
//! writing the codecs of the C# tooling suite under `tools/`.
//!
//! # Where this fits
//!
//! - Schema sources live under `schema/*.gschema` at the repository root.
//! - The CLI (`grimoire-schemagen`, `src/bin/grimoire-schemagen.rs`) hard-codes which schema
//!   produces which generated Rust file and which `docs/formats/*.md` page (project ADR-0011
//!   "Ort"): a schema describes a wire format, not a crate layout, so that mapping is the CLI's
//!   job, not the schema's.
//! - `.github/scripts/check-schemagen-drift.sh` reruns `grimoire-schemagen generate` and fails CI
//!   if that changes any checked-in file — the "generated code is current" gate Plan-0002 WP8.1
//!   requires.
//! - This crate itself has no `grimoire_*` dependency (not even a dev one) and is not part of the
//!   determinism set (no `clippy.toml`): nothing it emits runs at game time. It is recorded in
//!   contract §1's table and in engine ADR-0008's crate-map addendum (Nachtrag, WP8.1) as a
//!   dependency-free tool crate;
//!   `.github/scripts/check-crate-map.sh`'s `NO_ENGINE_EDGE_TOOL_CRATES` lists it explicitly so
//!   the crate-map check's full-workspace-membership pass still accounts for it even though it
//!   has no `grimoire_*` edge for that check's edge-based pass to ever see.
//!
//! # What this crate does *not* generate
//!
//! Frame envelopes, handshakes, pack headers/TOCs and SHA-256 verification stay hand-written on
//! purpose (project ADR-0011 "Vorschlag" point 1): they are control flow with only a few fields
//! each, not a wire-format vocabulary a schema compiler earns its keep describing. Building the
//! debug protocol's `Message` enum, its `to_frame`/`from_frame` dispatch and the handshake state
//! machine on top of the types this crate generates is Plan-0002 WP8.2, not this crate.

pub mod emit_csharp;
pub mod emit_docs;
pub mod emit_rust;
pub mod ir;
pub mod parser;

use std::path::Path;

/// Reads and parses the schema file at `path`, filling in [`ir::Schema::source_path`] from `path`
/// itself (backslashes normalised to `/` so the traceability comment [`emit_rust::emit`] and
/// [`emit_docs::emit`] write is identical whether this ran on Windows or on a CI Linux/macOS
/// runner — the same "no platform-dependent generated bytes" requirement that motivates every
/// other choice in this crate's output, project ADR-0011 "Negativ").
///
/// # Errors
/// Returns a human-readable message if `path` cannot be read or its contents fail to parse.
pub fn load_schema_file(path: &Path) -> Result<ir::Schema, String> {
    let text = std::fs::read_to_string(path)
        .map_err(|error| format!("failed to read {}: {error}", path.display()))?;
    let mut schema =
        parser::parse(&text).map_err(|error| format!("{}: {error}", path.display()))?;
    schema.source_path = path.to_string_lossy().replace('\\', "/");
    Ok(schema)
}
