//! The checked-in byte-wise golden fixture of the `FNP_CLIP` payload (contract §2 rule 10:
//! "byteweise Golden-Fixtures unter Versionskontrolle"; engine ADR-0017; format document
//! `docs/formats/figure-clip.md`).
//!
//! Two independent things are checked here, and the second is the point:
//!
//! 1. `fixtures/figure_clip_v1.bin` decodes into exactly the clip its derivation describes.
//! 2. `fixtures/figure_clip_v1.bin` equals `fixtures/figure_clip_v1.hex`, the hand-written
//!    field-by-field derivation, byte for byte. That listing was written from the format document
//!    and not produced by this crate — its skeleton fingerprint comes from an independent
//!    re-implementation of `StableHasher` v1 and its float bit patterns were written out by hand —
//!    so the two files agreeing means the document, the fixture and the decoder agree. Without
//!    this, a fixture generated by the decoder itself would happily freeze a decoder bug.
//!
//! The same pattern as `grimoire_assets/tests/pack_format.rs` and its `pack_v1_sigil.hex`.

use grimoire_render::figure_clip::{
    CLIP_FORMAT_VERSION, ClipSampler, decode_clip, sample_pose, skeleton_fingerprint,
};
use grimoire_render::figure_format::{JointData, SkeletonData, decode_skeleton};

const FIXTURE: &[u8] = include_bytes!("fixtures/figure_clip_v1.bin");

const LISTING_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/tests/fixtures/figure_clip_v1.hex"
);

/// The bytes of the annotated derivation `figure_clip_v1.hex`: hex bytes separated by whitespace,
/// everything after `#` a comment.
fn listing_bytes() -> Vec<u8> {
    let listing = std::fs::read_to_string(LISTING_PATH).expect("figure_clip_v1.hex");
    let mut bytes = Vec::new();
    for (number, line) in listing.lines().enumerate() {
        let code = line.split('#').next().unwrap_or("");
        for token in code.split_whitespace() {
            let byte = u8::from_str_radix(token, 16).unwrap_or_else(|_| {
                panic!(
                    "figure_clip_v1.hex line {}: `{token}` is not a hex byte",
                    number + 1
                )
            });
            bytes.push(byte);
        }
    }
    bytes
}

#[test]
fn the_fixture_equals_its_hand_written_derivation() {
    let listing = listing_bytes();
    assert_eq!(
        listing.len(),
        FIXTURE.len(),
        "figure_clip_v1.bin is {} bytes, its derivation {} bytes",
        FIXTURE.len(),
        listing.len()
    );
    for (offset, (&from_file, &from_listing)) in FIXTURE.iter().zip(listing.iter()).enumerate() {
        assert_eq!(
            from_file, from_listing,
            "figure_clip_v1.bin differs from its derivation figure_clip_v1.hex at offset {offset}"
        );
    }
}

#[test]
fn the_fixture_decodes_into_exactly_the_clip_its_derivation_describes() {
    let clip = decode_clip(FIXTURE).expect("the golden fixture decodes");
    assert_eq!(clip.joint_count(), 2);
    assert_eq!(clip.frame_count(), 3);
    assert_eq!(clip.frame_rate_hz(), 24.0);
    assert!(clip.is_looping());
    assert_eq!(clip.duration_seconds(), 2.0 / 24.0);
    assert_eq!(clip.skeleton_fingerprint(), 0x9a6c_8135_349d_1276);
    assert_eq!(clip.markers().len(), 1);
    assert_eq!(clip.markers()[0].frame, 1);
    assert_eq!(clip.markers()[0].name, "hit");
    assert_eq!(clip.marker_time("hit"), Some(1.0 / 24.0));

    // Joint 0's sampled translation, on each of the three frames.
    assert_eq!(sample_pose(&clip, 0.0)[0].translation, [0.0, 0.0, 0.0]);
    assert_eq!(
        sample_pose(&clip, 1.0 / 24.0)[0].translation,
        [0.0, 0.5, 0.0]
    );
    // Joint 1's sampled rotation, including the sign-flipped middle key, handed back verbatim.
    assert_eq!(
        sample_pose(&clip, 1.0 / 24.0)[1].rotation,
        [0.0, 0.0, 0.0, -1.0]
    );
    // Joint 1's constant translation.
    assert_eq!(sample_pose(&clip, 0.0)[1].translation, [0.0, 0.0, 1.0]);
}

#[test]
fn the_fixture_belongs_to_the_skeleton_its_derivation_names() {
    // The fingerprint in the fixture was computed by hand from "2 joints, parents -1 and 0". The
    // engine must arrive at the same number from an actual decoded skeleton of that shape, or the
    // format document is describing an algorithm nobody implements.
    let skeleton = ribbon_skeleton();
    assert_eq!(skeleton_fingerprint(&skeleton), 0x9a6c_8135_349d_1276);
    let clip = decode_clip(FIXTURE).expect("the golden fixture decodes");
    assert_eq!(clip.validate_against(&skeleton), Ok(()));
}

#[test]
fn the_fixture_composes_against_its_skeleton_without_an_error() {
    let skeleton = ribbon_skeleton();
    let clip = decode_clip(FIXTURE).expect("the golden fixture decodes");
    let mut sampler = ClipSampler::new();
    sampler.sample(&clip, 0.0);
    let matrices = sampler.skin_matrices(&skeleton).expect("matching counts");
    assert_eq!(matrices.len(), 2);
    // Frame 0 of the fixture is the rig's own rest pose, so the palette is the identity.
    let rest = grimoire_render::figure_format::rest_pose_skin_matrices(&skeleton);
    assert_eq!(matrices, rest.as_slice());
}

#[test]
fn a_single_flipped_byte_of_the_fixture_never_panics_the_decoder() {
    // Cheap, exhaustive version of the property test in `figure_clip`'s own test module: every
    // byte of the real fixture, set to a handful of awkward values.
    for offset in 0..FIXTURE.len() {
        for value in [0x00u8, 0x01, 0x7F, 0x80, 0xFF] {
            let mut bytes = FIXTURE.to_vec();
            bytes[offset] = value;
            let _ = decode_clip(&bytes);
        }
    }
}

/// The two-joint rig the fixture was authored for, decoded from an `FNP_SKELETON` payload rather
/// than built as a value, so the fingerprint is computed over what a pack would actually carry.
fn ribbon_skeleton() -> SkeletonData {
    let mut buf = Vec::new();
    buf.extend_from_slice(&1u32.to_le_bytes()); // FNP_SKELETON version
    buf.extend_from_slice(&2u32.to_le_bytes()); // joint_count
    for (parent, name, bind_z) in [(-1i32, &b"root"[..], 0.0f32), (0, &b"limb"[..], -1.0)] {
        buf.extend_from_slice(&parent.to_le_bytes());
        for column in [
            [1.0f32, 0.0, 0.0, 0.0],
            [0.0, 1.0, 0.0, 0.0],
            [0.0, 0.0, 1.0, 0.0],
            [0.0, 0.0, bind_z, 1.0],
        ] {
            for value in column {
                buf.extend_from_slice(&value.to_le_bytes());
            }
        }
        buf.push(u8::try_from(name.len()).expect("short fixture names"));
        buf.extend_from_slice(name);
    }
    for translation_z in [0.0f32, 1.0] {
        for value in [0.0f32, 0.0, translation_z] {
            buf.extend_from_slice(&value.to_le_bytes());
        }
        for value in [0.0f32, 0.0, 0.0, 1.0] {
            buf.extend_from_slice(&value.to_le_bytes());
        }
        for value in [1.0f32; 3] {
            buf.extend_from_slice(&value.to_le_bytes());
        }
    }
    let skeleton = decode_skeleton(&buf).expect("the fixture skeleton payload decodes");
    assert_eq!(skeleton.joints.len(), 2);
    let _: &JointData = &skeleton.joints[0];
    skeleton
}

#[test]
fn the_fixture_declares_the_format_version_this_crate_reads() {
    assert_eq!(CLIP_FORMAT_VERSION, 1);
    assert_eq!(&FIXTURE[8..12], &CLIP_FORMAT_VERSION.to_le_bytes());
}
